"""Dependency and license inventory.

Reuse over reimplementation is required, and it comes with an obligation: every
third-party dependency this repository pins is declared with its exact version and
license before the gate goes green. The inventory is derived from the two places
versions are actually pinned -- the Dockerfile's apt install block and
requirements.txt -- so adding a dependency without declaring it fails rather than
passing silently.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

APT_BLOCK = re.compile(r"apt-get install[^\n]*\n(.*?)&& rm -rf", re.DOTALL)
APT_TOKEN = re.compile(r"^\s*([a-z0-9][a-z0-9+.-]*)(?:=(\S+))?\s*$", re.MULTILINE)
LINE_CONTINUATION = chr(92)  # apt install lines are backslash-continued
# Extras are part of the name a requirements file pins ("psycopg[binary]"), so the
# inventory has to recognise them or a real dependency looks undeclared.
PIP_PIN = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9._-]*(?:\[[A-Za-z0-9,._-]+\])?)==(\S+)\s*$", re.MULTILINE
)


def pinned(dockerfile: Path, requirements: Path) -> dict[str, tuple[str, str]]:
    """Every third-party package this image installs, with the version it is pinned to."""
    found: dict[str, tuple[str, str]] = {}
    block = APT_BLOCK.search(dockerfile.read_text(encoding="utf-8"))
    if block:
        text = block.group(1).replace(LINE_CONTINUATION, " ")
        for name, version in APT_TOKEN.findall(text):
            found[name] = (version or "unpinned", "apt")
    if requirements.exists():
        for name, version in PIP_PIN.findall(requirements.read_text(encoding="utf-8")):
            found[name] = (version, "pip")
    return found


def render(declared: dict[str, dict[str, str]], found: dict[str, tuple[str, str]]) -> str:
    lines = [
        "# Dependency and License Inventory",
        "",
        "Generated by `tools/license_inventory.py`. Do not edit by hand; edit",
        "`docs/dependencies.toml` and re-run `make deps-write`.",
        "",
        "| Dependency | Version | Source | License | Why |",
        "|---|---|---|---|---|",
    ]
    for name in sorted(found):
        version, source = found[name]
        entry = declared.get(name, {})
        lines.append(
            f"| `{name}` | {version} | {source} | {entry.get('license', 'UNDECLARED')} "
            f"| {entry.get('why', 'UNDECLARED')} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--dockerfile", type=Path, default=Path("Dockerfile"))
    parser.add_argument("--requirements", type=Path, default=Path("requirements.txt"))
    parser.add_argument("--declared", type=Path, default=Path("docs/dependencies.toml"))
    parser.add_argument("--out", type=Path, default=Path("docs/DEPENDENCIES.md"))
    args = parser.parse_args()

    found = pinned(args.dockerfile, args.requirements)
    declared_raw = tomllib.loads(args.declared.read_text(encoding="utf-8"))
    declared: dict[str, dict[str, str]] = declared_raw.get("dependency", {})

    problems: list[str] = []
    for name, (version, source) in sorted(found.items()):
        entry = declared.get(name)
        if entry is None:
            problems.append(f"{name} ({source} {version}) is installed but not declared")
            continue
        if entry.get("version") != version:
            problems.append(
                f"{name} declared version {entry.get('version')!r} != installed {version!r}"
            )
        if not entry.get("license"):
            problems.append(f"{name} has no license recorded")
        if not entry.get("why"):
            problems.append(f"{name} has no justification recorded")
    for name in sorted(set(declared) - set(found)):
        problems.append(f"{name} is declared but no longer installed; remove it")

    rendered = render(declared, found)
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != rendered:
            problems.append(f"{args.out} is stale; run `make deps-write`")
        for problem in problems:
            print(f"deps: FAIL {problem}", file=sys.stderr)
        if problems:
            return 1
        print(f"deps: {len(found)} dependencies declared with licenses")
        return 0

    args.out.write_text(rendered, encoding="utf-8")
    print(f"deps: wrote {args.out} ({len(found)} dependencies)")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
